#!/usr/bin/env python3

import sys
from recrypt_electrum import Network
from recrypt_electrum.util import json_encode, print_msg
from recrypt_electrum import recrypt

try:
    addr = sys.argv[1]
except Exception:
    print("usage: get_history <recrypt_address>")
    sys.exit(1)

n = Network()
n.start()
_hash = recrypt.address_to_scripthash(addr)
h = n.synchronous_get(('blockchain.scripthash.get_history', [_hash]))
print_msg(json_encode(h))
